# Generated by Django 4.0.6 on 2022-07-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'managed': True},
        ),
    ]
