# Generated by Django 4.0.6 on 2022-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_ticker_px_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='px_open',
            field=models.FloatField(null=True, verbose_name='px_open'),
        ),
    ]
