# Generated by Django 4.0.6 on 2022-07-26 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_ticker_px_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='px_high',
            field=models.FloatField(null=True, verbose_name='px_high'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='px_last',
            field=models.FloatField(null=True, verbose_name='px_last'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='px_low',
            field=models.FloatField(null=True, verbose_name='px_low'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='yticker',
            field=models.CharField(db_index=True, default='_', max_length=12, verbose_name='yticker'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
