# Generated by Django 4.0.6 on 2022-07-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_ticker_date_ticker_px_high_ticker_px_last_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='px_high',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='px_last',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='px_low',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='px_open',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='px_volume',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='yticker',
        ),
    ]
