# Generated by Django 4.0.6 on 2022-07-27 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0009_ticker_yticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='date'),
        ),
    ]
