# Generated by Django 4.0.6 on 2022-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0015_ticker_px_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexique',
            fields=[
                ('isin', models.CharField(max_length=12, verbose_name='isin')),
                ('bbg_ticker', models.CharField(max_length=14, verbose_name='bbg_ticker')),
                ('yf_ticker', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='yf_ticker')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('sector', models.CharField(max_length=16, verbose_name='sector')),
                ('gics_sub_sector', models.CharField(max_length=100, verbose_name='gics_sub_sector')),
                ('id_zone', models.CharField(max_length=2, verbose_name='id_zone')),
                ('country', models.CharField(max_length=15, verbose_name='country')),
                ('ccy', models.CharField(max_length=3, verbose_name='ccy')),
                ('adr', models.BooleanField(verbose_name='adr')),
                ('indu', models.BooleanField(verbose_name='indu')),
                ('ndx', models.BooleanField(verbose_name='ndx')),
                ('spx', models.BooleanField(verbose_name='spx')),
                ('tsx', models.BooleanField(verbose_name='tsx')),
                ('sxxp', models.BooleanField(verbose_name='sxxp')),
                ('ftsie', models.BooleanField(verbose_name='ftsie')),
                ('spi', models.BooleanField(verbose_name='spi')),
                ('nikkei', models.BooleanField(verbose_name='nikkei')),
                ('kospi', models.BooleanField(verbose_name='kospi')),
                ('hangseng', models.BooleanField(verbose_name='hangseng')),
                ('australia', models.BooleanField(verbose_name='australia')),
                ('no_index', models.BooleanField(verbose_name='no_index')),
                ('cybersecurity', models.BooleanField(verbose_name='cybersecurity')),
                ('petsfervor', models.BooleanField(verbose_name='petsfervor')),
                ('biodefense', models.BooleanField(verbose_name='biodefense')),
                ('adv_mat', models.BooleanField(verbose_name='adv_mat')),
                ('meta', models.BooleanField(verbose_name='meta')),
                ('ltp', models.BooleanField(verbose_name='ltp')),
            ],
        ),
    ]
