# Generated by Django 4.0.6 on 2022-08-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0019_alter_ticker_yticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexique',
            name='market',
            field=models.CharField(default='NA', max_length=9, verbose_name='market'),
        ),
    ]
