# Generated by Django 4.0.6 on 2022-08-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0020_lexique_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='yticker',
            field=models.ForeignKey(db_column='yticker', on_delete=django.db.models.deletion.PROTECT, to='ticker.lexique'),
        ),
    ]
