# Generated by Django 4.0.6 on 2022-08-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0021_alter_ticker_yticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexique',
            name='adr',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='australia',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='ftsie',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='hangseng',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='indu',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='kospi',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='ndx',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='nikkei',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='spi',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='spx',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='sxxp',
        ),
        migrations.RemoveField(
            model_name='lexique',
            name='tsx',
        ),
    ]
