# Generated by Django 4.0.6 on 2022-08-17 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('status_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='status_id')),
                ('htag', models.CharField(default='To be defined', max_length=16, verbose_name='htag')),
                ('user_id', models.BigIntegerField(verbose_name='user_id')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('screen_name', models.CharField(max_length=32, verbose_name='screen_name')),
                ('text', models.TextField(verbose_name='text')),
                ('source', models.CharField(max_length=64, verbose_name='source')),
                ('display_text_width', models.SmallIntegerField(verbose_name='display_text_width')),
                ('reply_to_status_id', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='reply_to_status_id')),
                ('reply_to_user_id', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='reply_to_user_id')),
                ('reply_to_screen_name', models.CharField(max_length=32, null=True, verbose_name='reply_to_screen_name')),
                ('is_quote', models.BooleanField(verbose_name='is_quote')),
                ('is_retweet', models.BooleanField(verbose_name='is_retweet')),
                ('favorite_count', models.SmallIntegerField(verbose_name='favorite_count')),
                ('retweet_count', models.IntegerField(verbose_name='retweet_count')),
                ('mention_screen_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=None)),
                ('lang', models.CharField(max_length=3, verbose_name='lang')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
