# Generated by Django 4.0.6 on 2022-08-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='htag',
            field=models.CharField(default='To be defined', max_length=64, verbose_name='htag'),
        ),
    ]
