# Generated by Django 4.0.6 on 2022-08-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='reply_to_screen_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='reply_to_screen_name'),
        ),
        migrations.AlterField(
            model_name='media',
            name='reply_to_status_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='reply_to_user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='replay_to_user_id'),
        ),
    ]
