# Generated by Django 4.0.6 on 2022-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
