# Generated by Django 4.0.6 on 2022-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='htag',
            field=models.CharField(default='To be defined', max_length=32, verbose_name='htag'),
        ),
    ]
