# Generated by Django 4.0.6 on 2022-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_reply_to_screen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='reply_to_status_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='reply_to_status_id'),
        ),
        migrations.AlterField(
            model_name='media',
            name='reply_to_user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='reply_to_user_id'),
        ),
    ]
