# Generated by Django 4.0.6 on 2022-08-20 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_htag_alter_media_reply_to_screen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mentions_screen_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
    ]
