# Generated by Django 4.0.6 on 2022-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_media_mentions_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mentions_screen_name',
            field=models.CharField(max_length=1024, verbose_name='mentions_screen_name'),
        ),
    ]
