# Generated by Django 4.0.6 on 2022-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_media_mentions_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='retweet_count',
            field=models.IntegerField(verbose_name='retweet_count'),
        ),
    ]
