# Generated by Django 4.0.6 on 2022-08-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_alter_media_retweet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.CharField(max_length=64, verbose_name='source'),
        ),
    ]
